### ISSUE TITLE
imagem docker não encontrada

### ISSUE THREAD

**Issue by rcmerlo** [dpereira/es-covid19-br#6]
docker container run --rm --name covid19-br --volume /Users/rodrigomerlo/es-covid19-br/data/output:/opt/covid19-br/data/output covid19-br ./run.sh
Unable to find image 'covid19-br:latest' locally
docker: Error response from daemon: pull access denied for covid19-br, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by dpereira** [comment]
Faltou uma instrução no README:

```
$ make build
$ make run
```

Pode retentar? :pray:
